[www]
clear_env = no

; PHP のエラー / 出力を FPM 経由で stderr へ流し、CloudWatch に集約する
catch_workers_output = yes
decorate_workers_output = no

; FPM のアクセスログを stderr へ
access.log = /proc/self/fd/2

; プロセス管理。Fargate の vCPU / memory に応じて調整すること
pm = ondemand
pm.max_children = 3
pm.process_idle_timeout = 10s
pm.max_requests = 500